In [1]:
import torch
import numpy as np

# Simple Manual Linear Regression

In [11]:
w = torch.tensor([3.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)

In [12]:
def forward(x):
    return w*x+b

In [16]:
x = torch.tensor([[3.], [7.]])
forward(x)

tensor([[10.],
        [22.]], grad_fn=<AddBackward0>)

# Simple Linear Regression

In [17]:
from torch.nn import Linear

In [18]:
torch.manual_seed(1)

In [19]:
model = Linear(in_features=1, out_features=1)
print(model.bias, model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [22]:
x = torch.tensor([[4.3], [3.1]])
print(model(x))

tensor([[1.7743],
        [1.1559]], grad_fn=<AddmmBackward>)


# Simple Linear Regression - Custom module

In [26]:
import torch.nn as nn
torch.manual_seed(1)

In [27]:
class LR(nn.Module):
    
    def __init__(self, input_size, output_size):
        super().__init__()
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        pred = self.linear(x)
        return pred

In [29]:
model = LR(1, 1)
model

LR(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

In [31]:
x = torch.tensor([[2.0], [3.3], [23232.22]])
y_hat = model.forward(x)
print(y_hat)

tensor([[ 8.1646e-02],
        [-1.7037e-01],
        [-4.5034e+03]], grad_fn=<AddmmBackward>)


In [33]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1939]], requires_grad=True), Parameter containing:
tensor([0.4694], requires_grad=True)]
